apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-outbox-worker
  namespace: payments
spec:
  replicas: 2
  selector:
    matchLabels: { app: payment-outbox-worker }
  template:
    metadata:
      labels: { app: payment-outbox-worker }
    spec:
      containers:
        - name: worker
          image: ghcr.io/coolspartak9819-rgb/payment-ledger-platform:latest
          command: ["/payment-worker"]
          env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: payment-platform, key: DATABASE_URL } }
            - name: NATS_URL
              valueFrom: { secretKeyRef: { name: payment-platform, key: NATS_URL } }
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 500m, memory: 256Mi }
          securityContext: { allowPrivilegeEscalation: false, readOnlyRootFilesystem: true, runAsNonRoot: true }
